model_name_or_path: ./models/Qwen/Qwen3-8B
adapter_name_or_path: ./checkpoints/qwen3-8b-conll2003-lora/checkpoint-400
template: qwen3
finetuning_type: lora
export_dir: ./checkpoints/qwen3-8b-conll2003-merged
export_size: 5
export_device: cpu
export_legacy_format: false
