model_name_or_path: ./models/Qwen/Qwen3-8B
adapter_name_or_path: ./checkpoints/qwen3-8b-scierc-lora-rank8
template: qwen3
finetuning_type: lora
export_dir: ./checkpoints/qwen3-8b-scierc-merged-rank8
export_size: 5
export_device: cpu
export_legacy_format: false
